# Site settings
# These are used to personalize your site. You access them via {{ site.title }}, 
# {{ site.email }} and so on. You can create any custom variable you like. They
# will be accessible in the templates via {{ site.myvariable }}.

title: Kankoda
description: >-
  Kankoda builds apps and products for iOS, iPadOS, tvOS, macOS and watchOS, using technologies like Swift, SwiftUI and Swift Package Manager. 

url: http://kankoda.com
rss_url: https://kankoda.com/feed.xml

copyright_year: 2023
copyright_owner: Kankoda Sweden AB
copyright_url: https://kankoda.com

appstore_url: https://apps.apple.com/us/developer/kankoda-sweden-ab/id516398918
email: info@kankoda.com
email_url: mailto:info@kankoda.com
github_url: https://github.com/kankoda
gumroad_url: https://kankoda.gumroad.com
mastodon_url: https://mastodon.social/@kankoda
mastodon_username: kankoda@mastodon.social
twitter_url: https://twitter.com/kankodahq
twitter_username: kankodahq

swift:      https://developer.apple.com/swift/
swiftui:    https://developer.apple.com/xcode/swiftui/
spm:        https://www.swift.org/package-manager/
docc:       https://www.swift.org/documentation/docc/#:~:text=DocC%20syntax%20—%20called%20documentation%20markup,%2C%20code%20listings%2C%20and%20asides.
kotlin:     https://kotlinlang.org
jetpack:    https://developer.android.com/jetpack/compose

stockholm:  https://www.google.com/maps/place/Stockholm,+Sweden/@59.3262131,17.8172499,11z/data=!3m1!4b1!4m6!3m5!1s0x465f763119640bcb:0xa80d27d3679d7766!8m2!3d59.3293235!4d18.0685808!16zL20vMDZteHM

emojikit:       https://kankoda.com/emojikit
keyboardkit:    https://keyboardkit.com
keyboardkitpro: https://keyboardkit.com/pro
licensekit:     https://kankoda.com/licensekit
wally:          https://wally.app

bambuser:       https://bambuser.com
cineasterna:    https://cineasterna.com/en
oribi:          https://oribi.se/en/
qapital:        https://qapital.com

assets: /assets/
header_image: /assets/logo/logo.png

header_pages:
  - index.html
  - pages/products.md
  - pages/blog.md

footer_sitemap:
  - index.html
  - pages/company.md
  - pages/projects.md
  - pages/products.md
  - pages/blog.md

footer_extra_title: Products
footer_extra:
  - pages/products/emojikit/emojikit.md
  - pages/products/keyboardkit/keyboardkit.md
  - pages/products/licensekit/licensekit.md
  - pages/products/wally/wally.md
  

collections_dir: collections

collections:
  apps:
    output: true
    permalink: /apps/:name/
  emojikit-features:
    output: true
    permalink: /emojikit/features/:name/
  licensekit-features:
    output: true
    permalink: /licensekit/features/:name/
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title

baseurl: ""
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from

defaults:
  -
    scope:
      type: "apps"
    values:
      layout: "app"
      hero-img-class: "icon"
  -
    scope:
      type: "emojikit-features"
    values:
      image: /assets/headers/emojikit.png
      layout: "emojikit-feature"
  -
    scope:
      type: "licensekit-features"
    values:
      image: /assets/headers/licensekit.png
      layout: "licensekit-feature"
  -
    scope:
      type: "pages"
    values:
      hero: ""
  -
    scope:
      type: "posts"
    values:
      author: "danielsaidi"
      layout: "post"

include:
  - .well-known/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/