- name: KeyboardKit
  url: https://keyboardkit.com
  icon: keyboardkit
  text: Create amazing custom keyboards with Swift and SwiftUI.
  app: 1
  sdk: 1

- name: LicenseKit
  url:  https://getlicensekit.com
  icon: licensekit
  text: Protect your Swift-based software with commercial licenses.
  sdk: 1

- name: EmojiKit
  url:  /emojikit
  icon: emojikit
  text: An emoji SDK for all major Apple platforms (iOS, macOS, tvOS and watchOS).
  gumroad_url: https://kankoda.gumroad.com/l/emojikit
  sdk: 1

- name: Wally
  url:  https://wally.app
  icon: wally
  text: Wally is a digital wallet for iOS and iPadOS.
  app: 1
  
- name: Appamini
  url:  https://appamini.com
  icon: appamini
  text: Appamini are educational apps for curious kids.
  app: 1
