- name: KeyboardKit
  url: https://keyboardkit.com
  image: keyboardkit
  
- name: LicenseKit
  url:  https://getlicensekit.com
  image: licensekit

- name: Wally
  url:  https://wally.app
  image: wally

- name: Appamini
  url:  https://appamini.com
  image: appamini

- name: Appamini2
  url:  https://appamini.com
  image: appamini